name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: microsoft
        java-version: 17
    - name: Install make
      run: sudo apt-get update && sudo apt-get install make
    - name: Lint
      run: make lint
    - name: Test
      run: make test
